### ISSUE TITLE
Support `browsingContext.handleUserPrompt`

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1010]
Efforts to support the command and its related events:
- [x] Implement `browsingContext.userPromptOpened`
- [x] Implement `browsingContext.handleUserPrompt`
- [x] Implement `browsingContext.userPromptClosed`
- [x] Add local e2e tests
- [x] Add WPT tests 
- [x] Fix issue with `ChromeDriver` - related to attempt at attaching when prompt is displayed.

**Comment by Lightning00Blade** [comment]
@whimboo Yeah its on my agenda and some other wpt test as well.

**Comment by whimboo** [comment]
Great. I'm asking because I will start myself with the implementation of user prompts soon so we are not colliding.

**Comment by lutien** [comment]
@Lightning00Blade, while writing the tests for `browsingContext.handleUserPrompt`, I've realized that we can not guarantee that a prompt is open to run the command successfully without the `browsingContext.userPromptOpened` event in the test. I've written some tests with `sleep`, and if you want, you can take a look here: https://phabricator.services.mozilla.com/D185555, but we are probably not going to land them like this. That's why I'm starting now to work on the open event and will update then the tests. Furthermore, I'll probably start working on the tests for the open event as well in a couple of days (if the implementation will go smooth). Let me know if you already have something or started implementing.

**Comment by Lightning00Blade** [comment]
Thanks for looking into this. I have not started with anything related to WPT. The only thing we have is our own E2E https://github.com/GoogleChromeLabs/chromium-bidi/blob/main/tests/browsing_context/test_user_prompt.py Which I saw the same issue you need the events so that you know that the Prompt exist.

**Comment by sadym-chromium** [comment]
I believe it's not fully implemented on our side. E.g. `test_browsingContext_close_prompt` does not work with `chromedriver`. Could you please extend the description?

**Comment by Lightning00Blade** [comment]
Closing as completed with the land of https://chromium.googlesource.com/chromium/src/+/9d08106f75a6835a134b69d9a30bec87ecd0376c in Canary.
