### ISSUE TITLE
Implement `browser.close`

### ISSUE THREAD

**Issue by Lightning00Blade** [GoogleChromeLabs/chromium-bidi#1117]
- [x] Mapper Implementation
- [x] Mapper Tests
- [x] WPT tests

**Comment by sadym-chromium** [comment]
I believe this is fully done

**Comment by Lightning00Blade** [comment]
There are still no WPT test, but I am not sure how to verify that the browser was killed and also how it will affect other test that follow.

**Comment by whimboo** [comment]
FYI therefore we have [two Firefox specific tests](https://searchfox.org/mozilla-central/source/testing/web-platform/mozilla/tests/webdriver/bidi/browser/close/close.py) because there is not a good and easy cross-browser solution yet. We use custom fixtures which actually check the browser's process id, which we send by default as part of the response's capabilities for the `New Session` command.
