### ISSUE TITLE
Should we author e2e tests in a forward-compatible manner?

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#1721]
For example, adding new attributes to local end structures is not a breaking changes in the spec but it will be a breaking change for e2e (and maybe for some wpt) tests that use assert === to check the entire structure shape. I believe we should treat all local end structs as extensible in our tests to avoid modifying all tests when there is a new attribute added. 

cc @sadym-chromium

**Comment by sadym-chromium** [comment]
Historically, the strict assertions were done in order to be aware of any protocol changes. This was reasonable when the amount of e2e tests was relatively low and the protocol was changing quite quick. 

The proposed  transition allowing for flexibility in adding fields in the responses without causing test failures. However, this shift introduces the possibility of introducing new fields without explicit awareness. A significant concern is that developers often rely on tests rather than directly examining the raw protocol. 

Having said that, in my experience I don't recall this was a problem, so I'm fine if we change protocol assertions from `==` to `<=`, if that reduces friction with an acceptable level of risks.

**Comment by OrKoN** [comment]
How does `<=` work?

**Comment by sadym-chromium** [comment]
Note that [there is a mechanism for `<=` assertion in place](https://github.com/GoogleChromeLabs/chromium-bidi/blob/12ff5db1030c3f0c54563eb1c73b581ae4ba624f/tests/session/test_subscription.py#L552), but it is not very ergonomic.

To increase usability, we can consider introducing something like [`recursive_compare`](https://github.com/whimboo/wpt/blob/ea603dae1819008406400994a8880a46b52d0194/webdriver/tests/bidi/__init__.py#L8).

**Comment by sadym-chromium** [comment]
In "<=" I mean "is sub-dictionary" comparison. It is already implemented in 2 ways:
* In mapper: [`AnyWithEntries`](https://github.com/GoogleChromeLabs/chromium-bidi/blob/12ff5db1030c3f0c54563eb1c73b581ae4ba624f/tests/session/test_subscription.py#L552), but it is not recursive.
* In WPT: [`recursive_compare`](https://github.com/whimboo/wpt/blob/ea603dae1819008406400994a8880a46b52d0194/webdriver/tests/bidi/__init__.py#L8).
