### ISSUE TITLE
Feature: show version in BiDi-CDP Mapper tab

### ISSUE THREAD

**Issue by joerg1985** [GoogleChromeLabs/chromium-bidi#2503]
The versions of the `WebDriver BiDi for Chromium` and the `Chrome` / `Chromium` browser do not match.
It would be nice to see the version in use of the `WebDriver BiDi for Chromium` inside the `BiDi-CDP Mapper` tab.

This would make things easier in case a new browser update is deployed or someone has to report an issue.

**Comment by Lightning00Blade** [comment]
First of all this is never shipped with the browser, for Chrome it's only shipped as part of ChromeDriver.
Because of that you should be able to know the ChromeDriver version you have downloaded/use.
You can then infer the version of `chromium-bidi` by checking which version was pinned for ChromeDriver at that tag.
Example for this with ChromeDriver 127.0.6533.99 can be found: 
https://source.chromium.org/chromium/chromium/src/+/refs/tags/127.0.6533.99:third_party/bidimapper/README.chromium
(Note: version there is not specified, but still there is a revision that is a commit hash from this repository)

If there is a specific use case that this does not cover please comment and I will take a look.
Closing as not planned.
